### ISSUE TITLE
Exploring Svelte for Bachelor's Thesis Report

### ISSUE THREAD

**Issue by TheWhipAbdel** [EgdeConsulting/ConexusAI#16]
```[tasklist]
### Tasks
- [x] write what is svelte
- [x] why svelte?
- [x] how svelte uses?
- [x] Include sources
- [ ] How svelte used with exempels from the code
```
