### ISSUE TITLE
Menu "Buttons" to send or/& download the chat

### ISSUE THREAD

**Issue by TheWhipAbdel** [EgdeConsulting/ConexusAI#19]
```[tasklist]
### Tasks
- [x] Make a buttons componant
- [x] The componant have input {parent, name, method, picture}
- [x] From figma get pictures and names to the buttons!
```

```[tasklist]
### Tasks
```

**Comment by TheWhipAbdel** [comment]
Closed with #22
