### ISSUE TITLE
Create database environment

### ISSUE THREAD

**Issue by DrEgde** [EgdeConsulting/ConexusAI#21]
```[tasklist]
### Tasks
- [x] Create Azure SQL Environment
- [x] Import bacpac to Azure SQL
- [x] Deploy bacpac into DB
```

```[tasklist]
### Acceptance list
- [ ] Data from datavarehuset exists in database
```
