### ISSUE TITLE
Create endpoint (notes)

### ISSUE THREAD

**Issue by TheWhipAbdel** [EgdeConsulting/ConexusAI#23]
```[tasklist]
### Tasks
- [x] Find and use placeholder for API
- [ ] make methode for GET
- [x] Make methode for POST
```

**Comment by TheWhipAbdel** [comment]
closed with #28
