### ISSUE TITLE
Test 3rd party REST API with GPT reply functionality

### ISSUE THREAD

**Issue by KE-Egde** [EgdeConsulting/ConexusAI#27]
```[tasklist]
### Tasks
- [x] Connect to `https://python-chat-api.onrender.com/python/prompt`
- [x] Use POST request
- [x] To send: `{ "prompt": "[INPUT]" }`
- [x] Answer: `{ "answer": "[REPLY]" }`
```

**Comment by KE-Egde** [comment]
This could be a usefull resource, perhaps;

![Image](https://github.com/EgdeConsulting/ConexusAI/assets/157687583/325a40e6-f5e8-4f4a-8491-931a52f1e337)

**Comment by TheWhipAbdel** [comment]
Closed with #29
