### ISSUE TITLE
connect to database with SQL queries

### ISSUE THREAD

**Issue by DrEgde** [EgdeConsulting/ConexusAI#42]
```[tasklist]
### Tasks
- [x] Connect to database
- [x] Get response from database
- [x] Ask SQL queries to database and get response
- [x] Provide structure of database to OpenAI
- [x] Create SQL queries with OpenAI towards database
```
