### ISSUE TITLE
Connect backend API to backend application

### ISSUE THREAD

**Issue by DrEgde** [EgdeConsulting/ConexusAI#47]
```[tasklist]
### Tasks
- [ ] create api code
- [ ] create function in backend to connect with api
- [ ] test if api and connection with backend works
```

**Comment by DrEgde** [comment]
Rebasing
