### ISSUE TITLE
Create an improved backendai

### ISSUE THREAD

**Issue by DrEgde** [EgdeConsulting/ConexusAI#71]
```[tasklist]
### Tasks
- [x] Get an SQL query
- [x] Create the full chain that uses SQL query to create a NL response
- [x] Add an SQL query checker to validate query before its being processed
```
